	private static void confirmBadRecordOrder(final SanityChecker.CheckRecord[] check, Record[] recs) {
		final SanityChecker c = new SanityChecker();
		final List records = Arrays.asList(recs);
		try {
			new Runnable() {
				public void run() {
					c.checkRecordOrder(records, check);
				}
			}.run();
		} catch (AssertionFailedError pass) {
			// expected during normal test
			return;
		}
		throw new AssertionFailedError("Did not get failure exception as expected");
	}

