	private static void confirmBadRecordOrder(final SanityChecker.CheckRecord[] check, Record[] recs) {
		final SanityChecker c = new SanityChecker();
		final List<Record> records = Arrays.asList(recs);
		try {
			new Runnable() {
				public void run() {
					c.checkRecordOrder(records, check);
				}
			}.run();
		} catch (AssertionError pass) {
			// expected during normal test
			return;
		}
		fail("Did not get failure exception as expected");
	}

